// flow-typed signature: f68e126dd8dcfe441f5e3793fe4e4a43
// flow-typed version: <<STUB>>/istanbul-instrumenter-loader_v^2.0.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'istanbul-instrumenter-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'istanbul-instrumenter-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'istanbul-instrumenter-loader/index' {
  declare module.exports: $Exports<'istanbul-instrumenter-loader'>;
}
declare module 'istanbul-instrumenter-loader/index.js' {
  declare module.exports: $Exports<'istanbul-instrumenter-loader'>;
}
