// flow-typed signature: f7f256ac276a13857b9e13b4f95cab18
// flow-typed version: <<STUB>>/rucksack-css_v^0.9.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rucksack-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rucksack-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rucksack-css/bin/cmd' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/dist/placeholder_polyfill.jquery.min.combo' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/dist/placeholder_polyfill.jquery.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/docs/demo' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/Gruntfile' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/libs/jquery-1.6.2.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/libs/jquery.ba-resize.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/libs/jquery.onfontresize.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/libs/modernizr-2.0.6.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/libs/rAF.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/src/placeholder_polyfill.jquery' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5shiv/dist/html5shiv-printshiv' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5shiv/dist/html5shiv-printshiv.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5shiv/dist/html5shiv' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5shiv/dist/html5shiv.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/html5shiv/Gruntfile' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery.scrollTo/jquery.scrollTo' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery.scrollTo/jquery.scrollTo.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/dist/jquery' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/dist/jquery.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/ajax' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/ajax/jsonp' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/ajax/load' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/ajax/parseJSON' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/ajax/parseXML' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/ajax/script' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/ajax/var/nonce' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/ajax/var/rquery' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/ajax/xhr' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/attributes' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/attributes/attr' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/attributes/classes' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/attributes/prop' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/attributes/support' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/attributes/val' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/callbacks' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/core' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/core/access' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/core/init' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/core/parseHTML' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/core/ready' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/core/var/rsingleTag' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/addGetHookIf' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/curCSS' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/defaultDisplay' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/hiddenVisibleSelectors' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/support' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/swap' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/var/cssExpand' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/var/getStyles' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/var/isHidden' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/var/rmargin' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/css/var/rnumnonpx' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/data' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/data/accepts' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/data/Data' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/data/var/data_priv' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/data/var/data_user' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/deferred' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/deprecated' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/dimensions' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/effects' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/effects/animatedSelector' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/effects/Tween' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/event' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/event/ajax' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/event/alias' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/event/support' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/exports/amd' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/exports/global' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/intro' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/jquery' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/manipulation' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/manipulation/_evalUrl' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/manipulation/support' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/manipulation/var/rcheckableType' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/offset' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/outro' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/queue' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/queue/delay' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/selector-native' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/selector-sizzle' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/selector' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/serialize' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/sizzle/dist/sizzle' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/sizzle/dist/sizzle.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/traversing' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/traversing/findFilter' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/traversing/var/rneedsContext' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/arr' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/class2type' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/concat' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/hasOwn' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/indexOf' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/pnum' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/push' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/rnotwhite' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/slice' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/strundefined' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/support' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/var/toString' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/jquery/src/wrap' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-actionscript' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-actionscript.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-apacheconf' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-apacheconf.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-applescript' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-applescript.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-aspnet' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-aspnet.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-autohotkey' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-autohotkey.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-bash' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-bash.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-brainfuck' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-brainfuck.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-c' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-c.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-clike' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-clike.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-coffeescript' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-coffeescript.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-core' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-core.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-cpp' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-cpp.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-csharp' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-csharp.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-css-extras' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-css-extras.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-css' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-css.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-dart' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-dart.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-eiffel' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-eiffel.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-erlang' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-erlang.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-fortran' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-fortran.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-fsharp' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-fsharp.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-gherkin' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-gherkin.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-git' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-git.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-go' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-go.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-groovy' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-groovy.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-haml' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-haml.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-handlebars' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-handlebars.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-haskell' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-haskell.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-http' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-http.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-ini' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-ini.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-jade' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-jade.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-java' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-java.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-javascript' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-javascript.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-jsx' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-jsx.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-julia' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-julia.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-keyman' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-keyman.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-latex' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-latex.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-less' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-less.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-lolcode' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-lolcode.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-makefile' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-makefile.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-markdown' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-markdown.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-markup' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-markup.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-matlab' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-matlab.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-nasm' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-nasm.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-nsis' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-nsis.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-objectivec' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-objectivec.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-pascal' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-pascal.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-perl' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-perl.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-php-extras' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-php-extras.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-php' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-php.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-powershell' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-powershell.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-python' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-python.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-r' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-r.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-rest' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-rest.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-rip' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-rip.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-ruby' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-ruby.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-rust' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-rust.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-sas' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-sas.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-sass' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-sass.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-scala' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-scala.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-scheme' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-scheme.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-scss' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-scss.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-smalltalk' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-smalltalk.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-smarty' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-smarty.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-sql' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-sql.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-stylus' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-stylus.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-swift' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-swift.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-twig' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-twig.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-typescript' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-typescript.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-vhdl' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-vhdl.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-wiki' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-wiki.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-yaml' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/components/prism-yaml.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/examples' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/autolinker/prism-autolinker' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/autolinker/prism-autolinker.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/file-highlight/prism-file-highlight' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/file-highlight/prism-file-highlight.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/highlight-keywords/prism-highlight-keywords' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/highlight-keywords/prism-highlight-keywords.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/ie8/prism-ie8' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/ie8/prism-ie8.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/line-highlight/prism-line-highlight' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/line-highlight/prism-line-highlight.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/line-numbers/prism-line-numbers' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/line-numbers/prism-line-numbers.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/show-invisibles/prism-show-invisibles' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/show-invisibles/prism-show-invisibles.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/show-language/prism-show-language' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/show-language/prism-show-language.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/wpd/prism-wpd' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/plugins/wpd/prism-wpd.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/prism' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/prism/vendor/promise' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/remodal/dist/remodal' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/remodal/dist/remodal.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/respond/cross-domain/respond.proxy' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/respond/dest/respond.matchmedia.addListener.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/respond/dest/respond.matchmedia.addListener.src' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/respond/dest/respond.min' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/respond/dest/respond.src' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/respond/Gruntfile' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/respond/src/matchmedia.addListener' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/respond/src/matchmedia.polyfill' {
  declare module.exports: any;
}

declare module 'rucksack-css/bower_components/respond/src/respond' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rucksack-css/bin/cmd.js' {
  declare module.exports: $Exports<'rucksack-css/bin/cmd'>;
}
declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/dist/placeholder_polyfill.jquery.min.combo.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5-placeholder-polyfill/dist/placeholder_polyfill.jquery.min.combo'>;
}
declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/dist/placeholder_polyfill.jquery.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5-placeholder-polyfill/dist/placeholder_polyfill.jquery.min'>;
}
declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/docs/demo.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5-placeholder-polyfill/docs/demo'>;
}
declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/Gruntfile.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5-placeholder-polyfill/Gruntfile'>;
}
declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/libs/jquery-1.6.2.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5-placeholder-polyfill/libs/jquery-1.6.2.min'>;
}
declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/libs/jquery.ba-resize.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5-placeholder-polyfill/libs/jquery.ba-resize.min'>;
}
declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/libs/jquery.onfontresize.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5-placeholder-polyfill/libs/jquery.onfontresize.min'>;
}
declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/libs/modernizr-2.0.6.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5-placeholder-polyfill/libs/modernizr-2.0.6.min'>;
}
declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/libs/rAF.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5-placeholder-polyfill/libs/rAF.min'>;
}
declare module 'rucksack-css/bower_components/html5-placeholder-polyfill/src/placeholder_polyfill.jquery.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5-placeholder-polyfill/src/placeholder_polyfill.jquery'>;
}
declare module 'rucksack-css/bower_components/html5shiv/dist/html5shiv-printshiv.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5shiv/dist/html5shiv-printshiv'>;
}
declare module 'rucksack-css/bower_components/html5shiv/dist/html5shiv-printshiv.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5shiv/dist/html5shiv-printshiv.min'>;
}
declare module 'rucksack-css/bower_components/html5shiv/dist/html5shiv.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5shiv/dist/html5shiv'>;
}
declare module 'rucksack-css/bower_components/html5shiv/dist/html5shiv.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5shiv/dist/html5shiv.min'>;
}
declare module 'rucksack-css/bower_components/html5shiv/Gruntfile.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/html5shiv/Gruntfile'>;
}
declare module 'rucksack-css/bower_components/jquery.scrollTo/jquery.scrollTo.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery.scrollTo/jquery.scrollTo'>;
}
declare module 'rucksack-css/bower_components/jquery.scrollTo/jquery.scrollTo.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery.scrollTo/jquery.scrollTo.min'>;
}
declare module 'rucksack-css/bower_components/jquery/dist/jquery.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/dist/jquery'>;
}
declare module 'rucksack-css/bower_components/jquery/dist/jquery.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/dist/jquery.min'>;
}
declare module 'rucksack-css/bower_components/jquery/src/ajax.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/ajax'>;
}
declare module 'rucksack-css/bower_components/jquery/src/ajax/jsonp.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/ajax/jsonp'>;
}
declare module 'rucksack-css/bower_components/jquery/src/ajax/load.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/ajax/load'>;
}
declare module 'rucksack-css/bower_components/jquery/src/ajax/parseJSON.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/ajax/parseJSON'>;
}
declare module 'rucksack-css/bower_components/jquery/src/ajax/parseXML.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/ajax/parseXML'>;
}
declare module 'rucksack-css/bower_components/jquery/src/ajax/script.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/ajax/script'>;
}
declare module 'rucksack-css/bower_components/jquery/src/ajax/var/nonce.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/ajax/var/nonce'>;
}
declare module 'rucksack-css/bower_components/jquery/src/ajax/var/rquery.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/ajax/var/rquery'>;
}
declare module 'rucksack-css/bower_components/jquery/src/ajax/xhr.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/ajax/xhr'>;
}
declare module 'rucksack-css/bower_components/jquery/src/attributes.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/attributes'>;
}
declare module 'rucksack-css/bower_components/jquery/src/attributes/attr.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/attributes/attr'>;
}
declare module 'rucksack-css/bower_components/jquery/src/attributes/classes.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/attributes/classes'>;
}
declare module 'rucksack-css/bower_components/jquery/src/attributes/prop.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/attributes/prop'>;
}
declare module 'rucksack-css/bower_components/jquery/src/attributes/support.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/attributes/support'>;
}
declare module 'rucksack-css/bower_components/jquery/src/attributes/val.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/attributes/val'>;
}
declare module 'rucksack-css/bower_components/jquery/src/callbacks.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/callbacks'>;
}
declare module 'rucksack-css/bower_components/jquery/src/core.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/core'>;
}
declare module 'rucksack-css/bower_components/jquery/src/core/access.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/core/access'>;
}
declare module 'rucksack-css/bower_components/jquery/src/core/init.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/core/init'>;
}
declare module 'rucksack-css/bower_components/jquery/src/core/parseHTML.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/core/parseHTML'>;
}
declare module 'rucksack-css/bower_components/jquery/src/core/ready.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/core/ready'>;
}
declare module 'rucksack-css/bower_components/jquery/src/core/var/rsingleTag.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/core/var/rsingleTag'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/addGetHookIf.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/addGetHookIf'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/curCSS.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/curCSS'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/defaultDisplay.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/defaultDisplay'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/hiddenVisibleSelectors.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/hiddenVisibleSelectors'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/support.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/support'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/swap.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/swap'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/var/cssExpand.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/var/cssExpand'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/var/getStyles.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/var/getStyles'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/var/isHidden.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/var/isHidden'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/var/rmargin.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/var/rmargin'>;
}
declare module 'rucksack-css/bower_components/jquery/src/css/var/rnumnonpx.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/css/var/rnumnonpx'>;
}
declare module 'rucksack-css/bower_components/jquery/src/data.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/data'>;
}
declare module 'rucksack-css/bower_components/jquery/src/data/accepts.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/data/accepts'>;
}
declare module 'rucksack-css/bower_components/jquery/src/data/Data.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/data/Data'>;
}
declare module 'rucksack-css/bower_components/jquery/src/data/var/data_priv.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/data/var/data_priv'>;
}
declare module 'rucksack-css/bower_components/jquery/src/data/var/data_user.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/data/var/data_user'>;
}
declare module 'rucksack-css/bower_components/jquery/src/deferred.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/deferred'>;
}
declare module 'rucksack-css/bower_components/jquery/src/deprecated.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/deprecated'>;
}
declare module 'rucksack-css/bower_components/jquery/src/dimensions.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/dimensions'>;
}
declare module 'rucksack-css/bower_components/jquery/src/effects.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/effects'>;
}
declare module 'rucksack-css/bower_components/jquery/src/effects/animatedSelector.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/effects/animatedSelector'>;
}
declare module 'rucksack-css/bower_components/jquery/src/effects/Tween.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/effects/Tween'>;
}
declare module 'rucksack-css/bower_components/jquery/src/event.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/event'>;
}
declare module 'rucksack-css/bower_components/jquery/src/event/ajax.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/event/ajax'>;
}
declare module 'rucksack-css/bower_components/jquery/src/event/alias.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/event/alias'>;
}
declare module 'rucksack-css/bower_components/jquery/src/event/support.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/event/support'>;
}
declare module 'rucksack-css/bower_components/jquery/src/exports/amd.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/exports/amd'>;
}
declare module 'rucksack-css/bower_components/jquery/src/exports/global.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/exports/global'>;
}
declare module 'rucksack-css/bower_components/jquery/src/intro.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/intro'>;
}
declare module 'rucksack-css/bower_components/jquery/src/jquery.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/jquery'>;
}
declare module 'rucksack-css/bower_components/jquery/src/manipulation.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/manipulation'>;
}
declare module 'rucksack-css/bower_components/jquery/src/manipulation/_evalUrl.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/manipulation/_evalUrl'>;
}
declare module 'rucksack-css/bower_components/jquery/src/manipulation/support.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/manipulation/support'>;
}
declare module 'rucksack-css/bower_components/jquery/src/manipulation/var/rcheckableType.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/manipulation/var/rcheckableType'>;
}
declare module 'rucksack-css/bower_components/jquery/src/offset.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/offset'>;
}
declare module 'rucksack-css/bower_components/jquery/src/outro.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/outro'>;
}
declare module 'rucksack-css/bower_components/jquery/src/queue.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/queue'>;
}
declare module 'rucksack-css/bower_components/jquery/src/queue/delay.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/queue/delay'>;
}
declare module 'rucksack-css/bower_components/jquery/src/selector-native.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/selector-native'>;
}
declare module 'rucksack-css/bower_components/jquery/src/selector-sizzle.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/selector-sizzle'>;
}
declare module 'rucksack-css/bower_components/jquery/src/selector.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/selector'>;
}
declare module 'rucksack-css/bower_components/jquery/src/serialize.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/serialize'>;
}
declare module 'rucksack-css/bower_components/jquery/src/sizzle/dist/sizzle.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/sizzle/dist/sizzle'>;
}
declare module 'rucksack-css/bower_components/jquery/src/sizzle/dist/sizzle.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/sizzle/dist/sizzle.min'>;
}
declare module 'rucksack-css/bower_components/jquery/src/traversing.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/traversing'>;
}
declare module 'rucksack-css/bower_components/jquery/src/traversing/findFilter.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/traversing/findFilter'>;
}
declare module 'rucksack-css/bower_components/jquery/src/traversing/var/rneedsContext.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/traversing/var/rneedsContext'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/arr.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/arr'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/class2type.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/class2type'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/concat.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/concat'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/hasOwn.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/hasOwn'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/indexOf.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/indexOf'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/pnum.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/pnum'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/push.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/push'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/rnotwhite.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/rnotwhite'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/slice.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/slice'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/strundefined.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/strundefined'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/support.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/support'>;
}
declare module 'rucksack-css/bower_components/jquery/src/var/toString.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/var/toString'>;
}
declare module 'rucksack-css/bower_components/jquery/src/wrap.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/jquery/src/wrap'>;
}
declare module 'rucksack-css/bower_components/prism/components.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-actionscript.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-actionscript'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-actionscript.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-actionscript.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-apacheconf.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-apacheconf'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-apacheconf.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-apacheconf.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-applescript.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-applescript'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-applescript.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-applescript.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-aspnet.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-aspnet'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-aspnet.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-aspnet.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-autohotkey.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-autohotkey'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-autohotkey.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-autohotkey.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-bash.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-bash'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-bash.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-bash.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-brainfuck.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-brainfuck'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-brainfuck.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-brainfuck.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-c.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-c'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-c.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-c.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-clike.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-clike'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-clike.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-clike.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-coffeescript.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-coffeescript'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-coffeescript.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-coffeescript.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-core.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-core'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-core.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-core.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-cpp.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-cpp'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-cpp.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-cpp.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-csharp.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-csharp'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-csharp.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-csharp.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-css-extras.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-css-extras'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-css-extras.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-css-extras.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-css.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-css'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-css.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-css.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-dart.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-dart'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-dart.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-dart.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-eiffel.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-eiffel'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-eiffel.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-eiffel.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-erlang.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-erlang'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-erlang.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-erlang.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-fortran.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-fortran'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-fortran.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-fortran.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-fsharp.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-fsharp'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-fsharp.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-fsharp.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-gherkin.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-gherkin'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-gherkin.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-gherkin.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-git.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-git'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-git.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-git.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-go.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-go'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-go.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-go.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-groovy.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-groovy'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-groovy.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-groovy.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-haml.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-haml'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-haml.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-haml.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-handlebars.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-handlebars'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-handlebars.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-handlebars.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-haskell.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-haskell'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-haskell.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-haskell.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-http.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-http'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-http.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-http.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-ini.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-ini'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-ini.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-ini.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-jade.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-jade'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-jade.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-jade.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-java.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-java'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-java.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-java.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-javascript.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-javascript'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-javascript.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-javascript.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-jsx.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-jsx'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-jsx.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-jsx.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-julia.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-julia'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-julia.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-julia.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-keyman.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-keyman'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-keyman.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-keyman.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-latex.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-latex'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-latex.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-latex.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-less.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-less'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-less.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-less.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-lolcode.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-lolcode'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-lolcode.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-lolcode.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-makefile.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-makefile'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-makefile.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-makefile.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-markdown.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-markdown'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-markdown.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-markdown.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-markup.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-markup'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-markup.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-markup.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-matlab.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-matlab'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-matlab.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-matlab.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-nasm.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-nasm'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-nasm.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-nasm.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-nsis.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-nsis'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-nsis.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-nsis.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-objectivec.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-objectivec'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-objectivec.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-objectivec.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-pascal.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-pascal'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-pascal.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-pascal.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-perl.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-perl'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-perl.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-perl.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-php-extras.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-php-extras'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-php-extras.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-php-extras.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-php.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-php'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-php.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-php.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-powershell.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-powershell'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-powershell.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-powershell.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-python.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-python'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-python.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-python.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-r.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-r'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-r.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-r.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-rest.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-rest'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-rest.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-rest.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-rip.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-rip'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-rip.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-rip.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-ruby.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-ruby'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-ruby.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-ruby.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-rust.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-rust'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-rust.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-rust.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-sas.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-sas'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-sas.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-sas.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-sass.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-sass'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-sass.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-sass.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-scala.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-scala'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-scala.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-scala.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-scheme.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-scheme'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-scheme.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-scheme.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-scss.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-scss'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-scss.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-scss.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-smalltalk.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-smalltalk'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-smalltalk.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-smalltalk.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-smarty.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-smarty'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-smarty.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-smarty.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-sql.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-sql'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-sql.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-sql.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-stylus.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-stylus'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-stylus.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-stylus.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-swift.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-swift'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-swift.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-swift.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-twig.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-twig'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-twig.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-twig.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-typescript.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-typescript'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-typescript.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-typescript.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-vhdl.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-vhdl'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-vhdl.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-vhdl.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-wiki.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-wiki'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-wiki.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-wiki.min'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-yaml.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-yaml'>;
}
declare module 'rucksack-css/bower_components/prism/components/prism-yaml.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/components/prism-yaml.min'>;
}
declare module 'rucksack-css/bower_components/prism/examples.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/examples'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/autolinker/prism-autolinker.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/autolinker/prism-autolinker'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/autolinker/prism-autolinker.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/autolinker/prism-autolinker.min'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/file-highlight/prism-file-highlight.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/file-highlight/prism-file-highlight'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/file-highlight/prism-file-highlight.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/file-highlight/prism-file-highlight.min'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/highlight-keywords/prism-highlight-keywords.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/highlight-keywords/prism-highlight-keywords'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/highlight-keywords/prism-highlight-keywords.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/highlight-keywords/prism-highlight-keywords.min'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/ie8/prism-ie8.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/ie8/prism-ie8'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/ie8/prism-ie8.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/ie8/prism-ie8.min'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/line-highlight/prism-line-highlight.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/line-highlight/prism-line-highlight'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/line-highlight/prism-line-highlight.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/line-highlight/prism-line-highlight.min'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/line-numbers/prism-line-numbers.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/line-numbers/prism-line-numbers'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/line-numbers/prism-line-numbers.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/line-numbers/prism-line-numbers.min'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/show-invisibles/prism-show-invisibles.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/show-invisibles/prism-show-invisibles'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/show-invisibles/prism-show-invisibles.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/show-invisibles/prism-show-invisibles.min'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/show-language/prism-show-language.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/show-language/prism-show-language'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/show-language/prism-show-language.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/show-language/prism-show-language.min'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/wpd/prism-wpd.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/wpd/prism-wpd'>;
}
declare module 'rucksack-css/bower_components/prism/plugins/wpd/prism-wpd.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/plugins/wpd/prism-wpd.min'>;
}
declare module 'rucksack-css/bower_components/prism/prism.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/prism'>;
}
declare module 'rucksack-css/bower_components/prism/vendor/promise.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/prism/vendor/promise'>;
}
declare module 'rucksack-css/bower_components/remodal/dist/remodal.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/remodal/dist/remodal'>;
}
declare module 'rucksack-css/bower_components/remodal/dist/remodal.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/remodal/dist/remodal.min'>;
}
declare module 'rucksack-css/bower_components/respond/cross-domain/respond.proxy.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/respond/cross-domain/respond.proxy'>;
}
declare module 'rucksack-css/bower_components/respond/dest/respond.matchmedia.addListener.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/respond/dest/respond.matchmedia.addListener.min'>;
}
declare module 'rucksack-css/bower_components/respond/dest/respond.matchmedia.addListener.src.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/respond/dest/respond.matchmedia.addListener.src'>;
}
declare module 'rucksack-css/bower_components/respond/dest/respond.min.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/respond/dest/respond.min'>;
}
declare module 'rucksack-css/bower_components/respond/dest/respond.src.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/respond/dest/respond.src'>;
}
declare module 'rucksack-css/bower_components/respond/Gruntfile.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/respond/Gruntfile'>;
}
declare module 'rucksack-css/bower_components/respond/src/matchmedia.addListener.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/respond/src/matchmedia.addListener'>;
}
declare module 'rucksack-css/bower_components/respond/src/matchmedia.polyfill.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/respond/src/matchmedia.polyfill'>;
}
declare module 'rucksack-css/bower_components/respond/src/respond.js' {
  declare module.exports: $Exports<'rucksack-css/bower_components/respond/src/respond'>;
}
declare module 'rucksack-css/index' {
  declare module.exports: $Exports<'rucksack-css'>;
}
declare module 'rucksack-css/index.js' {
  declare module.exports: $Exports<'rucksack-css'>;
}
